# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: '**/*.csproj'
  buildVersion: '1.0.0'  

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet Tool'
    
  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'

  # Restore dependencies
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(project)'
    displayName: 'Restore dependencies'

  # Build the project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(project)'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'Build project'

  # Pack and upload as an artifact
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      projects: '$(project)'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    displayName: 'Pack project'

  # Publish artifact to Azure Artifacts
  - script: |
      nuget.exe push -Source "https://pkgs.dev.azure.com/sharon088/FirstHelloWorld/_packaging/HelloWorldFeed/nuget/v3/index.json" -ApiKey az $(Build.ArtifactStagingDirectory)\*.nupkg
    displayName: 'Push package to Azure Artifacts feed'
