trigger:
- main
- develop

pool:
  name: Default

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: '**/*.csproj'
  Major: '1'
  Minor: '0'
  Patch: $(Build.BuildId)  # Automatically increments with each build
  buildVersion: "$(Major).$(Minor).$(Patch)" 
  SENDGRID_API_KEY: $(sendgridApiKey)

steps:
  - checkout: self
    fetchDepth: 0
  
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'  
      installationPath: $(Agent.ToolsDirectory)/dot

  - task: UseNode@1
    inputs:
      version: '23.x'
  
  - task: SonarQubePrepare@6
    condition: eq(variables['Build.SourceBranchName'], 'develop')
    inputs:
      SonarQube: 'SonarQubeForSonarCloud'  # name of the service connection created in Azure DevOps
      scannerMode: 'MSBuild'
      organization: 'sharonsonarcloud'
      projectKey: 'sharon088_FirstHelloWorld'  # Exact key from SonarCloud 
      projectName: 'FirstHelloWorld'  # Project name in SonarQube

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet Tool'
    
  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'

  # Restore dependencies
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(project)'
    displayName: 'Restore dependencies'

  # Build the project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(project)'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'Build project'
  
  - task: SonarQubeAnalyze@6
    condition: eq(variables['Build.SourceBranchName'], 'develop')
    inputs:
      jdkversion: 'JAVA_HOME_21_X64'

  # Publish Quality Gate Result task
  - task: SonarQubePublish@6
    condition: eq(variables['Build.SourceBranchName'], 'develop')
    inputs:
      pollingTimeoutSec: '300'

  # Pack artifact
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      projects: '$(project)'
      versioningScheme: 'byEnvVar' 
      versionEnvVar: 'buildVersion'
    displayName: 'Pack project with branch $(Build.SourceBranchName) and version $(buildVersion)'

  # Push package to Azure Artifacts
  - task: DotNetCoreCLI@2
    inputs:
      arguments: '--skip-duplicate'
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'cde17caf-1198-4a60-90b3-0703b5263860/834a9e3c-e662-4c26-8a33-a54324b7196b'
    displayName: 'Push nupkg to Artifact'

    # Print Version to Console
  - script: |
      echo "Version: $(buildVersion)"
    displayName: 'Print Version to Console'

  # Success Email - send if build is successful
  - task: SendGridEmail@2
    condition: succeeded()
    inputs:
      SendGridApiKey: '$(SENDGRID_API_KEY)'
      FromAddress: 'sharon088@gmail.com'
      ToAddresses: 'rotem23592@gmail.com'
      Subject: 'Pipeline Success - Azure DevOps Build'
      emailBodyFormat: 'InLine'
      EmailBody: |
        Pipeline has completed successfully.
        
        Build Number: $(Build.BuildNumber)
        Build ID: $(Build.BuildId)
        
        ## Additional Information
        - Source Branch: $(Build.SourceBranchName)
        - Project: $(project)

  # Failure Email - send if build fails
  - task: SendGridEmail@2
    condition: failed()
    inputs:
      SendGridApiKey: '$(SENDGRID_API_KEY)'
      FromAddress: 'sharon088@gmail.com'
      ToAddresses: 'rotem23592@gmail.com'
      Subject: 'Pipeline Failed - Azure DevOps Build'
      emailBodyFormat: 'InLine'
      EmailBody: |
        Pipeline has failed. Please check the logs for details.
        
        Build Number: $(Build.BuildNumber)
        Build ID: $(Build.BuildId)
        
        ## Additional Information
        - Source Branch: $(Build.SourceBranchName)
        - Project: $(project)




