name: $(Major).$(Minor).$(Patch) 

trigger:
- main

pool:
  name: Default

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: '**/*.csproj'
  Major: '1'
  Minor: '0'
  Patch: $(Build.BuildId)  # Automatically increments with each build
  buildVersion: "$(Major).$(Minor).$(Patch)"  

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet Tool'
    
  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'

  # Restore dependencies
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(project)'
    displayName: 'Restore dependencies'

  # Build the project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(project)'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'Build project'

  # Pack and upload as an artifact
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      projects: '$(project)'
      versioningScheme: 'byBuildNumber' 
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:PackageId=AzureHelloWorld.$(buildVersion)'
    displayName: 'Pack project with version $(buildVersion)'

  - script: |
      echo "Version: $(buildVersion)"
    displayName: 'Print Version to Console'

  # Publish artifact to Azure Artifacts
  - script: |
      nuget.exe push -Source "https://pkgs.dev.azure.com/sharon088/FirstHelloWorld/_packaging/HelloWorldFeed/nuget/v3/index.json" -ApiKey az $(Build.ArtifactStagingDirectory)\*.nupkg
    displayName: 'Push package to Azure Artifacts feed'
